version: '3.8'

services:
  # Servicio de la API Flask
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Sincroniza tu código local con el contenedor
    env_file:
      - .env    # Carga las variables de entorno desde el archivo .env
    depends_on:
      - db      # Se asegura de que la base de datos se inicie primero

  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Expone el puerto de la BD a tu máquina local (opcional)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: